### PR TITLE
Bump all deps, add rust-toolchain.yaml

### PR DESCRIPTION
**Pull request by dlq84**
This PR bumps all deps, adds a rust-toolchain.yaml and sets channel to Rust 1.75 (env_logger doesn't work with newer yet).

It also adds a new Error type for Pem parsing since parse_many now returns a Result.

Replaces testcert.p12 with the latest one

### CODE REVIEW

**Comment by NicklasWallgren** [comment]
Great!

It seems to be something wrong with the updated `testcert.p12`, neither the tests nor the examples ran successfully using the new p12 file. Could you please verify? 🙂 

It worked as expected using the cert from the 
https://github.com/e-identification/bankid/blob/master/pkg/resource/certificates/test.p12

image

**Comment by dlq84** [comment]
That's odd, cargo test works fine for me. The old cert did not work.

```bash
> cargo run --package bankid --example authenticate                                                           master
   Compiling bankid v0.1.0 (/home/dlq/dlq84/bankid-rs)
    Finished dev [unoptimized + debuginfo] target(s) in 1.21s
     Running `target/debug/examples/authenticate`
Authenticate {
    auto_start_token: "ca2376d5-3d66-4fbc-b51d-c0c268860257",
    order_ref: "3bce521e-c2e3-42f8-b6d2-8560de345587",
    qr_start_token: "6fa8692c-539a-4cb4-b3a0-c2da7a3a0c3e",
    qr_start_secret: "a607c978-cd02-4df6-93c5-9bfcd28044d4",
}
Collect {
    order_ref: "3bce521e-c2e3-42f8-b6d2-8560de345587",
    status: "pending",
    hint_code: "outstandingTransaction",
    completion_data: None,
}
Cancel
```

**Comment by dlq84** [comment]
And this is what I get with the old cert and the cert in your link:

```bash
---- test_authenticate stdout ----
thread 'test_authenticate' panicked at src/client.rs:37:52:
Could not create a client from the supplied config: Pkcs12Error { source: reqwest::Error { kind: Builder, source: Normal(ErrorStack([Error { code: 50856204, library: "digital envelope routines", function: "inner_evp_generic_fetch", reason: "unsupported", file: "crypto/evp/evp_fetch.c", line: 355, data: "Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()" }])) } }
```

**Comment by NicklasWallgren** [comment]
The issue seems to only affect MacOS, see https://github.com/sfackler/rust-native-tls/issues/19. 

Go ahead and merge, I'll look into the problem in a separate issue.

image

**Review by NicklasWallgren — APPROVED** [review]

**Comment by dlq84** [comment]
I wouldn't mind switching to rustls if that helps, I've had more luck with that in my Alpine docker images too.

**Comment by NicklasWallgren** [comment]
> I wouldn't mind switching to rustls if that helps, I've had more luck with that in my Alpine docker images too.
> 
> I'm running OpenSSL 3.2.1 on Linux.

Yeah, that might be a good idea.

**Pull request merged**
